### ISSUE TITLE
Cấu hình JDBC Resource / Persistence Unit

### ISSUE THREAD

**Issue by Vunb** [VNPT-Technology/nms-ejb#1]
Hiện tại dự án chưa được cấu hình JDBC Resource.
Cần cấu hình `JDBC Resource` và `Persistence Unit` cho Ejb Facecade sử dụng.

**Comment by Vunb** [comment]
@Flytothesky92 @thuha1993 đã cấu hình được chưa em ?

**Comment by Flytothesky92** [comment]
Đã cấu hình được appconfig
-Thêm file persistence.xml
-Thêm Resource + connectionpool

**Comment by Flytothesky92** [comment]
a check cho e
