### ISSUE TITLE
Thêm mới chức năng lấy danh sách các AP Template

### ISSUE THREAD

**Issue by Vunb** [VNPT-Technology/nms-ejb#11]
Thêm mới chức năng lấy danh sách các AP Template trên nhánh mới và thực hiện các bước theo thứ tự sau:

* Tạo entityClass trong module remote
* Tạo ApTemplateFacadeRemote
* Viết testcase với entityClass, ApTemplateFacadeRemote đã tạo ra (Viết testcase trước)
* Xử lý nghiệp vụ trong Ejb module
* Deploy và chạy test

**Comment by Vunb** [comment]
@Flytothesky92 @thuha1993 các bạn thực hiện chức năng này nhé !

**Comment by thuha1993** [comment]
vâng. :dart:

**Comment by Vunb** [comment]
Chức năng lấy AP Template, AP Firmware xong chưa các e nhỉ ?
