### ISSUE TITLE
Thêm mới API: findByVersion trong ApFirmwareFacadeRemote

### ISSUE THREAD

**Issue by Vunb** [VNPT-Technology/nms-ejb#13]
Thêm một hàm findByVersion trong ApFirmwareFacadeRemote

**Comment by Vunb** [comment]
@Flytothesky92 làm cùng @thuha1993 Api này nhé

**Comment by thuha1993** [comment]
a ơi, khi nào rảnh a check hộ bọn e với, xem có cần sửa j ko ạ. :)
