### ISSUE TITLE
Cung cấp API quản lý các Vendor

### ISSUE THREAD

**Issue by Vunb** [VNPT-Technology/nms-ejb#2]
Cung cấp API cho phép thêm/sửa/xóa các `Vendor` trên hệ thống.

* Thêm / Sửa / Xóa
* Tìm kiếm `Vendor` theo tên, theo ID

**Comment by Vunb** [comment]
làm nhanh em ơi :-1:

**Comment by thuha1993** [comment]
Anh ấy làm xong rồi ạ, nhưng ko push được lên nhánh ạ. :8ball:

**Comment by Vunb** [comment]
Vậy à. Em support Hải nhé ! :100:

**Comment by thuha1993** [comment]
Em support không thành công. :))

**Comment by Flytothesky92** [comment]
Đã hoàn thành thêm/sửa/xóa + chuẩn hóa VendorFacade. Anh check cho em với. :8ball:

**Comment by Vunb** [comment]
Hải hoàn thành VendorFacade trong hôm nay và close lại issue này nhé !

**Comment by Flytothesky92** [comment]
Anh ơi em xong rồi anh ạ. A check hộ e với
