### ISSUE TITLE
Cung cấp API quản lý các SSID

### ISSUE THREAD

**Issue by Vunb** [VNPT-Technology/nms-ejb#3]
Cung cấp API cho phép thêm/sửa/xóa các `SSID` trên hệ thống.

* Thêm / Sửa / Xóa
* Tìm kiếm `SSID` theo tên, theo ID

**Comment by thuha1993** [comment]
Đã hoàn thành việc cung cấp API cho phép thêm/sửa/xóa các SSID trên hệ thống.
