### ISSUE TITLE
Chuẩn hóa SsidFacade theo template SsidFacade2

### ISSUE THREAD

**Issue by Vunb** [VNPT-Technology/nms-ejb#5]
Cần chuẩn hóa PU và lớp Abstract --> Giúp giảm nhẹ các hàm cơ bản không viết :+1:

**Comment by thuha1993** [comment]
đã chuẩn hóa PU và Abstract. Anh kiểm tra cho e với. :)

**Comment by Vunb** [comment]
ok e
