### ISSUE TITLE
Kiểm tra các API cơ bản SSID, Vendor

### ISSUE THREAD

**Issue by Vunb** [VNPT-Technology/nms-ejb#6]
1. Review code 
2. test các tính năng
3. Merge code nếu thành công

**Comment by Vunb** [comment]
Đã thực hiện review với nhánh SSID, testcase thành công !
Cần thực hiện review Vendor ...

**Comment by thuha1993** [comment]
sao em down về mà ko Build with Dependencies được vậy a? :(((((((((

**Comment by thuha1993** [comment]
Những file Test a tạo ra có Gen được ra ko a? :(

**Comment by Vunb** [comment]
Có thể gen được ra khung thôi em ạ. Còn các bước kiểm định đúng là mình phải chỉnh sửa thêm để đáp ứng được yêu cầu của dự án :8ball:

**Comment by thuha1993** [comment]
file EjbClientManager quản lý các jndi.propertier và ejb.properties mình có gen ra được ko a? hay là tự viết ạ ?

**Comment by Vunb** [comment]
Tự viết e ạ. Giờ mình chỉ thêm vào file ejb.properties thôi :rocket:
