### ISSUE TITLE
Tạo issue yêu cầu cung cấp API model thêm mới cho hệ thống !

### ISSUE THREAD

**Issue by Vunb** [VNPT-Technology/nms-ejb#7]
Gen cơ sở dữ liệu tạo model + Ejb Facade quản lý #1
Gen cơ sở dữ liệu tạo model + Ejb Facade quản lý #2

**Comment by thuha1993** [comment]
a ơi, e close mấy cái isue của vendor vs ssid nhé. nhìn cho đỡ hoa mắt ạ. :v:
